Added dynamic schedule
cesium/seium.org pull request #112
Opened 2021-12-02 17:50 UTC by tiago-bacelar

2021-12-02 18:07 UTC, ruioliveira02 requested changes
Change JSON to use array of objects with the date being a property

2021-12-04 21:39 UTC, ruioliveira02 approved these changes

2021-12-05 15:16 UTC, feliciofilipe commented
Please solve the conflicts that arose from updates in the ff/refactoring. I advise you start by doing a rebase.

2021-12-09 23:32 UTC, feliciofilipe commented
Please solve the conflicts

2021-12-16 22:15 UTC, closed without merging