Add faqs
cesium/seium.org pull request #197
Opened 2022-01-10 20:35 UTC by mariajbp

2022-01-10 20:39 UTC, ruioliveira02 requested changes

2022-01-10 20:39 UTC, ruioliveira02 commented on data/faqs.json
> +        "description": "You can e-mail us to geral@seium.org or leave message us on our social media accounts."}
There is a  mistake: it should either be "leave us a message on our social media" (missing the a) or simply "leave a message on our social media"

2022-01-10 20:48 UTC, ruioliveira02 submitted a review, later dismissed

2022-01-11 12:13 UTC, feliciofilipe commented
I would wait for #154 to be fixed before merging this one.

@quantik-git can you take care of it?

2022-01-11 18:07 UTC, miguelbrandao requested changes
Please rebase this branch according to the instructions in #sei-tecnologia on Slack

2022-01-11 19:06 UTC, miguelbrandao approved these changes

2022-01-12 21:36 UTC, ruioliveira02 approved these changes

2022-01-13 00:00 UTC, merged