Add Hackathon Members TBA
cesium/seium.org pull request #198
Opened 2022-01-10 20:41 UTC by mariajbp

Added Hackathon jury and mentors to be announced

2022-01-10 20:46 UTC, ruioliveira02 commented
![image](https://user-images.githubusercontent.com/70754369/148836752-03f9ed44-335a-42bf-8043-a7bf7f64eaf1.png)
This should be changed before release. Probably not this PR though. Thoughts? @feliciofilipe @mariajbp 
Otherwise looks good!

2022-01-11 18:06 UTC, miguelbrandao requested changes
Rebase

2022-01-11 19:12 UTC, miguelbrandao approved these changes

2022-01-12 22:04 UTC, ruioliveira02 approved these changes

2022-01-13 00:00 UTC, merged