Make Navbar Responsive
cesium/seium.org pull request #201
Opened 2022-01-13 22:18 UTC by feliciofilipe

2022-01-13 22:49 UTC, nelsonmestevao commented on pages/index.js
> +      <Navbar bg_color="secondary" button="quinary" fg_color="black">
In JavaScript, variables (in this case props) should be camelCase.
```suggestion
      <Navbar bgColor="secondary" button="quinary" fgColor="black">
```

2022-01-14 00:57 UTC, miguelbrandao submitted a review, later dismissed

2022-01-14 09:01 UTC, ruioliveira02 requested changes
<img width="953" alt="image" src="https://user-images.githubusercontent.com/70754369/149488100-4cd2cd8b-3c98-45c8-a4a2-ff974403b398.png">
Please fix this warning and solve the conflict.

2022-01-14 10:28 UTC, mariajbp approved these changes

2022-01-14 20:10 UTC, nelsonmestevao commented on components/website/utils/Navbar/index.jsx
> +    // { name: 'Team', href: '/team' },
Keep in mind that this doesn't prevent the user to access `/team`.

2022-01-14 20:14 UTC, nelsonmestevao commented
![image](https://user-images.githubusercontent.com/19409687/149579132-0e426dc6-eb27-4c11-a297-9cd93d4d9376.png)

There's a styling bug when you open navbar in mobile and go back to desktop version. Not a big problem though but shouldn't be hard to fix with a `lg:`.

2022-01-14 20:16 UTC, nelsonmestevao commented
> Shouldn't there be an option to sign up to moonstone via the mobile navbar?

Anyway, I think this button is not to sign up in moonstone, but to register on Event Brite. When you do that, you receive an account. @mariajbp @miguelbrandao @jtexeira should check this flow.

Last year's edition the button in mobile went down:

![image](https://user-images.githubusercontent.com/19409687/149579389-fcd5935a-495c-46fc-a7fb-e24ef5ff4bbd.png)

2022-01-14 20:18 UTC, nelsonmestevao commented on components/website/utils/Navbar/index.jsx
> +export default function Navbar(props) {
Checkout https://2021.seium.org/ to see the mobile animation that we are missing.

2022-01-14 20:19 UTC, miguelbrandao commented
You are right @nelsonmestevao ,there is no sign-up, only the registration on moonstone

2022-01-14 21:49 UTC, feliciofilipe commented on components/website/utils/Navbar/index.jsx
> +    // { name: 'Team', href: '/team' },
Yeah, what should I do in this regard?

2022-01-14 21:56 UTC, feliciofilipe commented on components/website/utils/Navbar/index.jsx
> +    // { name: 'Team', href: '/team' },
I see, thanks :pray::pray::pray:

2022-01-14 21:57 UTC, feliciofilipe commented
@miguelbrandao @nelsonmestevao I am adding to the Join us button on the mobile version as in the previous edition

2022-01-14 22:00 UTC, feliciofilipe commented
> ![image](https://user-images.githubusercontent.com/19409687/149579132-0e426dc6-eb27-4c11-a297-9cd93d4d9376.png)
> 
> There's a styling bug when you open navbar in mobile and go back to desktop version. Not a big problem though but shouldn't be hard to fix with a `lg:`.

I am already doing this, I think its another situation on params in tailwind classes not working always

2022-01-14 22:35 UTC, feliciofilipe commented
@nelsonmestevao 

I think now its good and it looks really nice

<details>
<summary><strong>Previews</strong></summary>

![image](https://user-images.githubusercontent.com/55213469/149594066-3ed6ba60-e5ee-4cf2-9e7d-87f2167a8b04.png)
![image](https://user-images.githubusercontent.com/55213469/149594084-ee105ae9-cbdb-4bed-9d65-abfb00689658.png)
![image](https://user-images.githubusercontent.com/55213469/149594123-efcb4aa9-fa3b-4fd8-98dd-a27c5fd3efae.png)

</details>

2022-01-14 23:09 UTC, miguelbrandao approved these changes

2022-01-14 23:11 UTC, rubenadao approved these changes

2022-01-14 23:14 UTC, ruioliveira02 approved these changes

2022-01-14 23:14 UTC, merged