Add staff form to navbar
cesium/seium.org pull request #238
Opened 2022-01-19 22:18 UTC by mariajbp

Added link to the navbar with a form for staff

2022-01-19 22:19 UTC, miguelbrandao approved these changes

2022-01-20 10:55 UTC, ruioliveira02 approved these changes

2022-01-20 11:44 UTC, feliciofilipe approved these changes

2022-01-20 13:24 UTC, miguelbrandao requested changes
Resolve conflicts

2022-01-20 18:30 UTC, closed without merging