Update Schedule
cesium/seium.org pull request #262
Opened 2022-02-05 21:59 UTC by feliciofilipe

2022-02-05 22:40 UTC, nelsonmestevao approved these changes
:100:

2022-02-05 23:40 UTC, ruioliveira02 commented
Please resolve the conflicts and make sure the checks pass

2022-02-06 16:00 UTC, miguelbrandao requested changes
Remove the changes to package-lock

2022-02-08 17:36 UTC, miguelbrandao approved these changes

2022-02-08 17:39 UTC, mariajbp approved these changes

2022-02-08 18:09 UTC, merged