Connect leaderboard to Safira
cesium/seium.org pull request #265
Opened 2022-02-06 12:34 UTC by ruioliveira02

I am sure what to do if the request fails. Should the user be redirected to another page, should a message pop up?

2022-02-07 20:17 UTC, nelsonmestevao commented
> I am sure what to do if the request fails. Should the user be redirected to another page, should a message pop up?

I think in most cases, the best way to handle it is to show an error pop up. When the error in safira is a good message, just show it to the user. If the message is a bad error, just 'Something went wrong', sorry not sorry :D 

You could use just https://headlessui.dev/react/dialog. I guess is the best way using headlessui. You could also use https://www.npmjs.com/package/react-notifications, but it is not as good-looking in my opinion.

2022-02-07 23:29 UTC, ruioliveira02 commented
I implemented an error pop up. It is not much, so if you want it changed, say so

2022-02-08 16:26 UTC, nelsonmestevao commented
![image](https://user-images.githubusercontent.com/19409687/153030762-8aedfd9e-2d60-4a43-ba58-15c2ab22e6bf.png)


Login page and dashboard have those lines, and we cannot interact with the page :/

2022-02-08 18:26 UTC, miguelbrandao requested changes
There is something wrong with the styling
![image](https://user-images.githubusercontent.com/26719984/153052020-7bc360ab-ae2f-4026-9e31-353c160d8e58.png)

2022-02-08 18:26 UTC, miguelbrandao commented on pages/attendee/leaderboard.js
> +  useEffect(() => requestLeaderboard(), [leaderboard]);
The `[leaderboard]` here is (probably) inducing a bug of multiple requests

2022-02-08 18:28 UTC, miguelbrandao commented
> ![image](https://user-images.githubusercontent.com/19409687/153030762-8aedfd9e-2d60-4a43-ba58-15c2ab22e6bf.png)
> 
> Login page and dashboard have those lines, and we cannot interact with the page :/

@nelsonmestevao I cant reproduce in either Chrome or Firefox

2022-02-08 19:55 UTC, miguelbrandao approved these changes

2022-02-09 00:44 UTC, merged