Connect roulette to backend
cesium/seium.org pull request #274
Opened 2022-02-08 10:53 UTC by ruioliveira02

2022-02-10 19:28 UTC, miguelbrandao requested changes
Checkout the conflicts please. Also, I can't go to the wheel page. Going there automatically redirects me to the profile

2022-02-10 19:28 UTC, miguelbrandao commented on data/schedule.json
> +      },
Check this out please. It's probably unintended

2022-02-10 19:28 UTC, miguelbrandao commented on pages/attendee/wheel.js
> +      prob="2.00%"
Hardcoded?

2022-02-10 19:28 UTC, miguelbrandao commented on pages/attendee/wheel.js
> +              <p className="font-iregular">10 tokens💰</p>
The cost is 20 tokens

2022-02-10 19:29 UTC, ruioliveira02 commented on pages/attendee/wheel.js
> +              <p className="font-iregular">10 tokens💰</p>
Are you sure? In staging was only spending 10. I might be mistaken though

2022-02-10 19:31 UTC, ruioliveira02 commented on pages/attendee/wheel.js
> +      prob="2.00%"
There was no probability in the response

2022-02-11 21:01 UTC, miguelbrandao commented on pages/attendee/wheel.js
> +              <p className="font-iregular">10 tokens💰</p>
Yeah, it will be 20 this year. Glad you pointed it out though, it was also 10 in production by mistake

2022-02-11 21:13 UTC, miguelbrandao approved these changes
Is the wheel working? I see the code is there, but I can't spin it :(

2022-02-11 21:13 UTC, miguelbrandao commented on lib/api.js
> +  alert(JSON.stringify(response.data));
Remove this :laughing:

2022-02-11 21:13 UTC, miguelbrandao commented on pages/attendee/wheel.js
> +      prob="2.00%"
Let's remove the probability column. It isn't going to be used

2022-02-11 21:13 UTC, miguelbrandao requested changes
See comments above ^

2022-02-12 18:03 UTC, merged