Fixed date displayed on Schedule
cesium/seium.org pull request #392
Opened 2022-03-31 19:21 UTC by tiago-bacelar

Fixed date shown beyond the max date

2022-03-31 19:34 UTC, ruioliveira02 submitted a review, later dismissed

2022-04-01 11:16 UTC, miguelbrandao requested changes
Good job 💪 
I'll fix the tests in the meantime

2022-04-01 11:16 UTC, miguelbrandao commented on components/website/speakers/Schedule/index.jsx
> +  default_date = isAfter(default_date, max_date) ? max_date : default_date;
Change it so that if the date exceeds the last day, it shows the first day instead of the last. It makes more sense if you are looking at it in three years

2022-04-01 11:16 UTC, miguelbrandao commented on components/website/utils/Schedule/index.jsx
> +  default_date = isAfter(default_date, max_date) ? max_date : default_date;
Same here

2022-04-02 01:52 UTC, miguelbrandao commented
Tests _should_ be fixed

2022-08-06 19:30 UTC, merged