refactor(AuthContext): Refactor to TypeScript and change dir
cesium/seium.org pull request #404
Opened 2022-12-07 22:30 UTC by EnzoVieira

Change AuthContext from /components to /context

2022-12-07 22:39 UTC, EnzoVieira commented on context/Auth/AuthContext.tsx
> -  // Make the provider update only when it should
I've deleted this useMemo because it's generally used just for complex calcs (that is not this case).

This useMemo causes two renders, the first one because the states changed and second because the useMemo detects that someone from it's dependency array changed, causing unecessary renders.

2023-10-25 20:11 UTC, ruilopesm commented on context/Auth/AuthContext.tsx
> +import * as USER from "../../lib/user";
We could maybe create a `@lib`?

2023-11-02 11:56 UTC, tiago-bacelar requested changes
Don't forget to run the formatter :)
After that, I think it's good to merge (if the github actions cooperate)

2023-11-10 12:49 UTC, diogogmatos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor AuthContext: Refactor to TypeScript and change dir](https://trello.com/c/iX5vtSiE/14-refactor-authcontext-refactor-to-typescript-and-change-dir)

2023-11-11 17:17 UTC, tiago-bacelar approved these changes

2023-11-11 17:33 UTC, tiago-bacelar commented
I took the opportunity of refactoring the auth context to fix an old bug logging in/out, where an error would appear in the console saying something along the lines of "Abort fetching route 'attendee/profile' ". To solve that, I added a new feature: much like blackboard, when you try to access a protected page while unauthenticated, instead of simply redirecting away, the original route is stored as a query param. That way, after the login is complete, the user is redirected to the original route.
It wasn't a marked issue or anything, it was just bugging me for a while :)

2023-11-30 16:50 UTC, ruilopesm commented on context/Auth/AuthContext.tsx
> +import * as api from "@lib/api";
Why both imports?

2023-11-30 16:50 UTC, ruilopesm commented on context/Auth/AuthContext.tsx
> +type ISopnsor = any;
```suggestion
type ISponsor = any;
```

2023-11-30 16:50 UTC, ruilopesm commented on context/Auth/AuthContext.tsx
> +// FIXME: Change this types from any
We should type this based on what safira sends.

2024-01-24 19:02 UTC, joaodiaslobo approved these changes
Looks good! 🚀

2024-01-24 21:57 UTC, merged