Micro generator to ensure new file system
cesium/seium.org pull request #410
Opened 2023-01-07 16:59 UTC by EnzoVieira

Since we are now refactoring the file system for this project, I think that this would be very useful to ensure our new structure consistency. It also will help our team to save time when creating new Components or Layouts, preventing them from wasting their time trying to figure out the pattern.

I've used Plop that is a "micro-generator framework" and should save our team from [context switching](https://www.petrikainulainen.net/software-development/processes/the-cost-of-context-switching/) when dealing with others repo that use a different pattern

This lib works as a CLI, using `npm run plop`
<img width="334" alt="Captura de Tela 2023-01-07 às 16 58 28" src="https://user-images.githubusercontent.com/73349819/211161870-88f51878-d1b1-4e43-9ea4-903de02ea12b.png">

2023-01-07 17:07 UTC, EnzoVieira commented
Some examples:

<img width="470" alt="Captura de Tela 2023-01-07 às 17 06 13" src="https://user-images.githubusercontent.com/73349819/211162263-aafa2fd2-980c-41ea-8acf-f6e06c1ea108.png">
<img width="492" alt="Captura de Tela 2023-01-07 às 17 06 40" src="https://user-images.githubusercontent.com/73349819/211162282-81d843e9-6bed-4cf8-ba16-25532711970c.png">

2023-01-07 17:12 UTC, RuiL1904 commented on generator/plopfile.js
> +        message: "Shoul add moduled styles?",
```suggestion
        message: "Should add moduled styles?",
```

2023-01-07 17:12 UTC, RuiL1904 commented on generator/plopfile.js
> +        message: "Shoul add components folder used only in this layout?",
```suggestion
        message: "Should add components folder used only in this layout?",
```

2023-01-07 17:15 UTC, EnzoVieira commented on generator/plopfile.js
> +        message: "Shoul add components folder used only in this layout?",
ops 😅
done ✅

2023-01-08 12:15 UTC, RuiL1904 submitted a review, later dismissed
Great job 🚀

2023-01-08 12:16 UTC, RuiL1904 requested changes
Make sure "Code Quality" check is passing 🙏🏼

2023-01-08 18:29 UTC, feliciofilipe commented
You probably want to merge this to: `ff/refactor-filesystem`, right @EnzoVieira ?

2023-01-08 20:52 UTC, EnzoVieira commented
> You probably want to merge this to: `ff/refactor-filesystem`, right @EnzoVieira ?

I thought that since this feature does not affect the frontend itself, it could be already in main. but on second thought, maybe it's better to merge into your branch to bring this new feat just when the new file system is done 😅.

i'm gonna change that 🙏🏻

2023-01-09 10:12 UTC, RuiL1904 approved these changes

2023-01-09 16:37 UTC, merged