ref(pages/product): Change page and image background color
cesium/seium.org pull request #455
Opened 2023-02-07 19:40 UTC by EnzoVieira

Also refactor page to new filesystem

resolve #417

2023-02-08 14:58 UTC, ruioliveira02 reviewed
Can you disable the button when the attendee does not have enough tokens to purchase?
Also can you change the navbar to the attendee one. Ideally that would be refactored and generalized in another PR, but I think it should be changed still

2023-02-09 09:05 UTC, MarioRodrigues10 requested changes

2023-02-09 09:05 UTC, MarioRodrigues10 commented on layout/Product/Product.tsx
> +const navigation = ["dashboard", "spotlight"];
Navigation for this page should be 
["profile", "wheel", "badgedex","leaderboard","store","vault"]

Which are the routes that attendee as access to

2023-02-09 15:06 UTC, ruioliveira02 approved these changes
This is not good code, it is working code. This will need a lot of refactor :sweat_smile:

2023-02-09 15:06 UTC, merged