Add leaderboard to staff/admin dashboard
cesium/seium.org pull request #485
Opened 2023-02-18 19:28 UTC by feliciofilipe

2023-02-18 20:47 UTC, RuiL1904 reviewed
Shouldn't `Leaderboard` be a shared component between `Attendee` and `Manager` layouts? With this approach we are not repeating the exact same code between different layouts.

2023-02-18 21:20 UTC, EnzoVieira requested changes

2023-02-18 21:20 UTC, EnzoVieira commented on layout/Manager/Leaderboard/Leaderboard.tsx
> +    >
Add `basePath="manager"` prop to Layout component. This way the user would be redirected to `/manager/leaderboard` instead of `/attendee/leaderboard`

2023-02-18 21:20 UTC, EnzoVieira commented on layout/Manager/Leaderboard/index.ts
> +export { default } from "./Leaderboard";
I also think that `Leaderboard` should become a shared layout between manager and admin pages, instead of a layout inside `/layout/Manager`. 

I'd suggest adding another folder inside layout folder called `Shared`, this way we know that all the layouts that are inside this folder are used in more than one page.

2023-11-05 15:28 UTC, tiago-bacelar requested changes
Since we already have a folder components, I don't think it makes sense to put the leaderboard inside layout/shared
Also, since you removed the navigation field in the manager routes, could you please do the same in all the sponsor routes as well? That way we could remove the navigation argument from the Layout altogether. I think that would be nice :)
Also, the leaderboard link is missing from the landing. It's in components/Navbar/index.jsx.

2023-11-06 10:53 UTC, tiago-bacelar approved these changes

2023-11-06 12:12 UTC, merged