build: Update to Next 13
cesium/seium.org pull request #490
Opened 2023-08-23 11:04 UTC by ruioliveira02

2023-09-03 18:28 UTC, RuiL1904 reviewed
![image](https://github.com/cesium/seium.org/assets/76881129/ecda0e9e-563b-40c3-a0f8-7e488d11f372)
Does this happen to you too?

2023-10-22 16:31 UTC, EnzoVieira requested changes

2023-10-22 16:31 UTC, EnzoVieira commented on layout/Attendee/Store/components/Product/index.tsx
>        passHref
I think this passHref is no longer needed

https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

2023-10-22 16:31 UTC, EnzoVieira commented on layout/ResetPassword/components/ResetPasswordForm/index.tsx
>              <Link href="/login" passHref>
Here as well

2023-10-22 16:31 UTC, EnzoVieira commented on components/Base/index.jsx
> +                    passHref
Here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Base/index.jsx
> +                  passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Dashboard/index.jsx
> +            <Link href="/" className="px-4 font-iregular text-quinary" passHref>
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Navbar/index.jsx
> +                            passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Navbar/index.jsx
> +                            passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Navbar/index.jsx
> +                                      passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Base/index.jsx
> +                    passHref
I think this `passHref` is no longer needed

https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

2023-10-22 16:31 UTC, EnzoVieira commented on components/Base/index.jsx
> +                  passHref
here as well

2023-10-22 16:31 UTC, EnzoVieira commented on components/Dashboard/index.jsx
> +            <Link href="/" className="px-4 font-iregular text-quinary" passHref>
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Footer/index.tsx
>                passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Footer/index.tsx
> +              passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Navbar/index.jsx
> +                            passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on components/Navbar/index.jsx
> +                                      passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on layout/Attendee/Store/components/Product/index.tsx
>        passHref
here

2023-10-22 16:31 UTC, EnzoVieira commented on layout/ResetPassword/components/ResetPasswordForm/index.tsx
>              <Link href="/login" passHref>
here

2023-10-26 13:36 UTC, EnzoVieira submitted a review, later dismissed
Great job! 🚀

2023-11-04 21:16 UTC, MarioRodrigues10 approved these changes
:+1:

2023-11-04 21:16 UTC, merged