feat: improve wheel design
cesium/seium.org pull request #560
Opened 2023-10-26 15:05 UTC by joaodiaslobo

Resolves #535 

<img width="617" alt="image" src="https://github.com/cesium/seium.org/assets/30907944/f6aa889c-7298-4046-8db9-f4fd09ea7135">

2023-10-27 22:49 UTC, tiago-bacelar reviewed
Nice. Since you're working on this though, could you pls do a couple extra things?
- The time delay is implemented inside api.js and that is driving me nuts. Can you please pull it out into Wheel.tsx?
- The token count is only updated after the 5 second delay. Could you also make it update before? Note that you can't run refetchUser, since that would already return any wins immediately, so instead you can just remove 20 tokens manually.
Also, you could have just put isSpinning inside canSpin() :)

2023-10-28 01:39 UTC, MarioRodrigues10 requested changes

2023-10-28 01:39 UTC, MarioRodrigues10 commented on layout/Attendee/Wheel/Wheel.tsx
> +            //TODO:: CHANGE THIS MESSAGE
```suggestion
```

2023-10-28 01:39 UTC, MarioRodrigues10 commented on layout/Attendee/Wheel/Wheel.tsx
> +              <p className="select-none font-iregular">20 tokens💰</p>
This shouldn't be hardcoded but should be grapped from the safira environment, but do it in another PR

2023-10-28 01:45 UTC, MarioRodrigues10 approved these changes
:rocket:

2023-10-28 01:45 UTC, merged