chore: standardize buttons using a button component
cesium/seium.org pull request #571
Opened 2023-11-10 08:52 UTC by MarioRodrigues10

chore: use a Button component

2023-11-10 12:42 UTC, diogogmatos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Standardize buttons using a button component](https://trello.com/c/m4kxN5gc/8-standardize-buttons-using-a-button-component)

2023-11-10 22:56 UTC, joaodiaslobo requested changes

2023-11-10 22:56 UTC, joaodiaslobo commented on pages/register/[uuid].js
> +            title="submit"
This doesn't look quite right 🤔
![image](https://github.com/cesium/seium.org/assets/30907944/56abf120-902f-4209-966b-b33369e6ae03)

2023-11-11 11:27 UTC, ruilopesm commented on components/Button/index.tsx
> +  description?: string;
Why does a button have a description? 🤔

2023-11-11 17:53 UTC, MarioRodrigues10 commented on components/Button/index.tsx
> +  description?: string;
There's a lot of buttons who has like a second title or a subtitle, for example in store the button has a title "Redeem" with a subtitle "X tokens".

2023-11-11 18:06 UTC, tiago-bacelar reviewed
I feel like the title field could be a child component. I know 99% of the time it's text, but for the other 1% it would be really useful. Not to mention, it would be less verbose, more intuitive and better follow the composition model of react.

2023-11-13 01:18 UTC, Darguima reviewed
I would suggest take the `...rest` of the Button Props and pass it to the button element, to allow to use the generic HTML button props at the component level, without need future changes or extra complexity.

I think that if you don't want do this, at least you should correct the Props types with the Typescript Pick or Omit operators, because at this moment is correct, at the typescript level, pass any of the HTML buttons props to this component, even if they aren't used.

![image](https://github.com/cesium/seium.org/assets/49988070/f5d4d0bf-c70a-40a9-8101-67e6b7a8c567)

Also, if you want accept the changes I think that would be better the `customStyle` be the `className` (already included at ...rest) so as not to create confusion, since they would overwrite the other

2023-11-13 01:18 UTC, Darguima commented on components/Button/index.tsx
> +  bold,
```suggestion
  bold,
  ...rest
```

2023-11-13 01:18 UTC, Darguima commented on components/Button/index.tsx
>      <button
```suggestion
    <button
      {...rest}
```

2023-11-24 21:15 UTC, Darguima requested changes

2023-11-24 21:15 UTC, Darguima commented on components/Button/index.tsx
> +  title: string;
Change this type to `ReactNode`

2023-11-24 21:15 UTC, Darguima commented on components/Button/index.tsx
> +  title: string;
Change this type to `ReactNode`

2023-11-25 22:57 UTC, Darguima submitted a review, later dismissed

2023-11-26 00:06 UTC, Darguima approved these changes
Perfect

2023-11-26 18:30 UTC, merged