Add see password button to authentication pages
cesium/seium.org pull request #572
Opened 2023-11-10 15:37 UTC by Darguima

Added see Password Button at all login/signup forms, except the one at `pages/register/[uuid].js` (I'm wating for feedback  in how access this page).

I also needed edit Input Component to accept and `right children` component, like exists at React Native and others UI libraries.

Issue related: https://github.com/cesium/seium.org/issues/527

![image](https://github.com/cesium/seium.org/assets/49988070/d65608f3-5ad9-49a0-9f12-26e01c9c7a4a)

2023-11-11 11:33 UTC, ruilopesm commented on layout/Login/components/LoginForm/index.tsx
> +                className="mx-2"
```suggestion
                className="cursor-pointer mx-2"
```

2023-11-11 11:33 UTC, ruilopesm commented on layout/ResetPassword/components/ResetPasswordForm/index.tsx
> +                className="mx-2"
```suggestion
                className="cursor-pointer mx-2"
```

2023-11-11 11:34 UTC, ruilopesm commented on layout/SignUp/components/SignUpForm/index.tsx
> +              className="mx-2"
```suggestion
              className="cursor-pointer mx-2"
```

2023-11-11 11:34 UTC, ruilopesm commented on layout/SignUp/components/SignUpForm/index.tsx
> +              className="mx-2"
```suggestion
              className="cursor-pointer mx-2"
```

2023-11-11 11:34 UTC, ruilopesm commented on layout/ResetPassword/components/ResetPasswordForm/index.tsx
> +                className="mx-2"
```suggestion
                className="cursor-pointer mx-2"
```

2023-11-11 11:35 UTC, ruilopesm commented on pages/register/[uuid].js
> +                className="mx-2"
```suggestion
                className="cursor-pointer mx-2"
```

2023-11-11 11:35 UTC, ruilopesm commented on pages/register/[uuid].js
> +                className="mx-2"
```suggestion
                className="cursor-pointer mx-2"
```

2023-11-11 17:57 UTC, tiago-bacelar reviewed
I think this is a great opportunity to create a PasswordInput component. There's a lot of duplicated code running around, and the extra useStates everywhere just to show/hide the eye are really cluttery.
You could even use the regular Input to create the PasswordInput, although I think it would be best to separate the two. That way you could also remove the right children from the Input, which would literally never be used for anything other than the eye icon on a password input.

2023-11-12 18:50 UTC, Darguima commented
@tiago-bacelar @ruilopesm , I agree with you that creating a new component is a good idea.

You mentioned not using the Input component, so should I create a new independent component, right? In that case, I'll need to duplicate some code, mainly the styles. Is that not a problem?

I understand the idea of removing the 'right' prop, and I think it's better to have the styles repeated than that right prop. However, is there a way to avoid repeating the styles? Because if, for some reason, somebody changes the Input styles, it would also be necessary to edit them in PasswordInput, and this can be forgotten.

(by now I will create the component from the right prop, to already replace everything with the component, then I edit consonant your feedback)

2023-11-12 18:51 UTC, Darguima commented on layout/Login/components/LoginForm/index.tsx
> +                className="mx-2"
I will add this to the component that I will create

2023-11-12 18:51 UTC, Darguima commented on layout/SignUp/components/SignUpForm/index.tsx
> +              className="mx-2"
I will add this to the component that I will create

2023-11-12 18:51 UTC, Darguima commented on layout/ResetPassword/components/ResetPasswordForm/index.tsx
> +                className="mx-2"
I will add this to the component that I will create

2023-11-12 18:51 UTC, Darguima commented on pages/register/[uuid].js
> +                className="mx-2"
I will add this to the component that I will create

2023-11-13 21:21 UTC, ruilopesm approved these changes
Great work 🙌🏼

2023-11-13 23:22 UTC, tiago-bacelar requested changes

2023-11-13 23:22 UTC, tiago-bacelar commented on layout/SignUp/components/SignUpForm/index.tsx
> +        <PasswordInput text="PASSWORD" fgColor="white" bgColor="primary" />
Hey! Great work. Just a little bug here though: you removed the onChange, but forgot to replace it with a ref, so none of the password inputs are registering any text.

2023-11-13 23:22 UTC, tiago-bacelar commented on pages/register/[uuid].js
> +          <PasswordInput text="PASSWORD" fgColor="white" bgColor="primary" />
Same thing in these two, no ref

2023-11-13 23:22 UTC, tiago-bacelar commented on layout/SignUp/components/SignUpForm/index.tsx
> -          id="password"
Just one more thing. Since you didn't specify the name and id of any of the password inputs, both are the default ("password"). I don't think this causes any problems (because we aren't using the id or the name for anything), but it is a bad practice to have duplicated ids and names. Honestly, I think removing the name and id fields from the PasswordInput is the best way of avoiding this. If it is REALLY necessary to specify either, the programmer can still do so because of the {...rest}

2023-11-15 15:58 UTC, diogogmatos commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: add password visibility button to authentication pages](https://trello.com/c/K9yNfthK/23-feat-add-password-visibility-button-to-authentication-pages)

2023-11-19 13:41 UTC, Darguima commented on layout/SignUp/components/SignUpForm/index.tsx
> -          id="password"
I didn't specified here the  `name` and `id` because, if you see the code, both components already had the same `id`/`name`. But yes I will remove them from the component.

2023-11-19 13:46 UTC, Darguima commented on pages/register/[uuid].js
> +          <PasswordInput text="PASSWORD" fgColor="white" bgColor="primary" />
I will add the onChange that already existed

2023-11-21 23:20 UTC, Darguima commented
I already fix the requested changes about the id/name prop. I added the id/name prop again, and fix it from `password` to `confirm` on the password confirmations inputs.

Also, to delete the right prop from the Input component, I created the PasswordInput without any dependency on the Input, but to avoid repeated styles, that could cause different styles, after a modification at only one of the component, I exported the Input styles from the Input component. What do you think of the result? (I know that isn't the most common thing, so I'm waiting feedback)

2023-11-24 20:22 UTC, Darguima commented
To prevent repeated styles across the project were created a InputBase wrapper to be used internally when creating Input components.

2023-11-24 21:00 UTC, tiago-bacelar approved these changes
Good job! :muscle:

2023-11-24 21:07 UTC, merged