Infinite Scroll Badgedex
cesium/seium.org pull request #578
Opened 2023-11-24 12:51 UTC by Darguima

2023-11-24 21:20 UTC, joaodiaslobo requested changes
Can you use this badge image instead?
<img width="387" alt="image" src="https://github.com/cesium/seium.org/assets/30907944/338c6d6e-2d74-45e2-9b32-a2b24fd49552">

2023-11-24 22:41 UTC, Darguima commented
I already edited, but the 404 have a buggy shadow

![image](https://github.com/cesium/seium.org/assets/49988070/13e4738d-862b-4795-abf5-40a4469d19fb)

2023-11-24 22:46 UTC, Darguima commented
Fixed

![image](https://github.com/cesium/seium.org/assets/49988070/83c71360-6680-4951-9a7f-a18aece710e0)

2023-11-25 12:47 UTC, ruilopesm commented on components/Badge/index.tsx
> +        <img src={avatar} onError={imageOnError} alt="Badge Image"></img>
```suggestion
        <img src={avatar} onError={imageOnError} alt={name}></img>
```
For accessibility reasons.

2023-11-27 20:13 UTC, ruilopesm reviewed
Great work 🙌🏼
In fact, this is not an infinite scroll, as the content is not being loaded as I scroll down. However, I feel that approach is over complicated and not necessary here. Anyway, I think we should implement a skeleton rendering for when a badge is rendering - can you handle that? 💪🏼

2023-12-04 01:45 UTC, Darguima commented
> Great work 🙌🏼 In fact, this is not an infinite scroll, as the content is not being loaded as I scroll down. However, I feel that approach is over complicated and not necessary here. Anyway, I think we should implement a skeleton rendering for when a badge is rendering - can you handle that? 💪🏼

Done. Any suggestions or any already existing color schema on the project that I can use here for the skeleton?

Also, I suggest you to try because the video is a little bit confusing on the transition due quick access to the image.


https://github.com/cesium/seium.org/assets/49988070/a564664a-2ab2-40b9-9a9e-406a8d787a4f

2023-12-06 11:45 UTC, Darguima commented
I fixed that delay showing the fallback image after the skeleton. Also fixed the infinite loop fallback.

2023-12-07 17:45 UTC, merged