feat: add course to attendee
cesium/seium.org pull request #579
Opened 2023-11-24 18:59 UTC by joaodiaslobo

Add course selection to user on signup and edit profile, also fixes #533 since some changes were needed to add the new select course input to user profile. Depends on safira [#341](https://github.com/cesium/safira/issues/341).
 
 
<img width="330" alt="image" src="https://github.com/cesium/seium.org/assets/30907944/0fc38321-0137-4466-b994-e644c4e913df">

<img width="527" alt="image" src="https://github.com/cesium/seium.org/assets/30907944/fec1ad92-6670-4904-a259-c5e77b6f02f8">

2023-11-24 19:02 UTC, joaodiaslobo commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: add course to attendee](https://trello.com/c/GEWIEKmt/51-feat-add-course-to-attendee)

2023-11-24 20:46 UTC, MarioRodrigues10 requested changes
Please add the degree that an attendee is currently in (Bachelors, Masters or PhD)

2023-11-27 09:46 UTC, ruioliveira02 commented on components/Input/index.tsx
> +            enabled == false ? "text-gray-500" : textColor
```suggestion
            enabled ? textColor : "text-gray-500"
```

2023-11-27 09:46 UTC, ruioliveira02 commented on pages/register/[uuid].js
> +      course,
I might be missing something, but shouldn't you need the UUID here as well?

2023-11-27 11:00 UTC, joaodiaslobo commented on pages/register/[uuid].js
> +      course,
That's a mistake, thanks for the heads up! 🙏

2023-11-29 23:09 UTC, ruilopesm approved these changes

2023-11-29 23:17 UTC, merged