chore: remove placeholder data for public release and hide unused pages
cesium/seium.org pull request #598
Opened 2023-12-13 02:24 UTC by joaodiaslobo

First public release version of the platform for the 2024 edition.
- Add 2024 SEI team (using placeholder images).
- All unused pages removed from routing.
- Fix minor design inconsistencies.
- Remove `typewriter-effect` animation library (replaced it with a simple fade in animation, in the future we will have to remake the writing animation without using that library since it causes deployment errors, but for now this will have to do).
- Remove Join Us button from Home page (Eventbrite registration isn't available yet, when it opens, we will have to find a better design for this button since it doesn't fit the current scheme).
- Update partners
- Update FAQs

2023-12-13 02:34 UTC, joaodiaslobo commented
![](https://github.trello.services/images/mini-trello-icon.png) [chore: remove placeholder data for public release and hide unused pages](https://trello.com/c/3yRZPDHW/67-chore-remove-placeholder-data-for-public-release-and-hide-unused-pages)

2023-12-14 22:43 UTC, MarioRodrigues10 requested changes

2023-12-14 22:43 UTC, MarioRodrigues10 commented on data/faqs.json
> +    "href": "https://www.instagram.com/cesiuminho/",
```suggestion
    "href": "https://www.instagram.com/sei.uminho/",
```

2023-12-14 22:46 UTC, MarioRodrigues10 approved these changes
:rocket:

2023-12-14 22:48 UTC, merged