feat: add twitter social
cesium/seium.org pull request #619
Opened 2024-01-15 07:42 UTC by feliciofilipe

Just wanted to add another contribution to make sure I keep those that wish to take my place as _top contributor_ at bay. 

When I was registering to make sure I got the early bird badge I noticed that there was not the twitter social. I know there is not a SEI twitter but it does not hurt to have CeSIUM since we share the SEI stuff there and it always help with increasing the following in multiple platforms. 

Also, twitter is the main social network in tech (unless you consider GitHub a social network and in that case you are a nerd).

The guy that did this component was dumb (me) and used a `grid`, I change it to a `flexbox` as god intended. 

**If there is a badge for opening a PR to this codebase during the next SEI, I'm pre-ordering it**

[Preview](https://www.youtube.com/watch?v=xvFZjo5PgG0)

2024-01-15 12:11 UTC, ruilopesm submitted a review, later dismissed

2024-01-15 12:14 UTC, joaodiaslobo commented
This has already been approve but I'm afraid adding another icon to the list causes some issues on mobile resolutions. It's not that big of a deal since it only happens on certain conditions but maybe we could study a better solution.

<img width="255" alt="image" src="https://github.com/cesium/seium.org/assets/30907944/d2cfb575-2067-492a-8c62-cc29f7c7e748">

2024-01-15 17:43 UTC, tiago-bacelar requested changes
The footer socials are off-center. I did a little digging and its because the div they're placed in has a fixed width (sm:w-1/2). Removing that should fix it
![image](https://github.com/cesium/seium.org/assets/70779845/d5034bea-9310-48e7-9761-e9d2b9210325)

2024-01-31 23:46 UTC, joaodiaslobo approved these changes

2024-01-31 23:48 UTC, merged